bool zbFwCheck();
void zbHwCheck();
bool zbLedToggle();
bool zigbeeErase();
void nvPrgs(const String &inputMsg);
void zbEraseNV(void *pvParameters);
void flashZbUrl(String url);
void flashZbFile(const char *filePath, const char *originalFilename = nullptr);
bool eraseWriteZbUrl(const char *url, std::function<void(float)> progressShow, CCTools &CCTool);
bool eraseWriteZbFile(const char *filePath, std::function<void(float)> progressShow, CCTools &CCTool);
String extractChipModelFromFilename(const char *filePath);
bool validateChipModel(const char *filePath, const char *currentChipModel);
